version: '3'
services:
  client:
    image: 'joaquinmw1994/multi-container-frontend'
    mem_limit: 128m
    hostname: client
  server:
    image: 'joaquinmw1994/multi-container-backend'
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  worker:
    image: 'joaquinmw1994/multi-container-worker'
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: 'joaquinmw1994/multi-container-nginx'
    mem_limit: 128m
    hostname: nginx
    ports:
      - '80:80'
